development:
  secret_key_base: key
  publishable_key: pk_test_51LUoXFCkgvvHYXAVvccVWv4CS78p5HaUHbBhJc0vqlfl8ae9Vrlr2gdZbBwopZqG4n41QaKAwzJdXGHVn864RTZx00ddVKpEG4
  secret_key: sk_test_51LUoXFCkgvvHYXAVzpiIWTlqBaB3qStCWCWN0zvi9xl5IIRp3pUM3BQeXwsq9Az6GYCYOviloIis0L7fXZGCiX6G00EWVqNm8g
